### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by Deadfalt999** [xenia-manager/experimental-builds#2]
I put it in it's own folder to test it out and when I open it, there's a CMD window that opens, a few lines scroll and then "This Program has stopped responding" appears (The Windows Pop-Up).

I'm on Windows 10 Pro 22H2 (build 19045.6036)

**Comment by Adad-G** [comment]
Do you have .NET 9.0 installed on your system? If not, download and install the latest version: https://dotnet.microsoft.com/es-es/download/dotnet/9.0

Edit: Although it opens now, it's very buggy at the moment.

**Comment by Deadfalt999** [comment]
I'm sorry I've been away, this isssue happenes still even though I have .NET 9.0 is installed.

**Comment by shazzaam7** [comment]
Post Logs to help me see whats wrong

**Comment by shazzaam7** [comment]
Okay, I've downloaded and installed Windows 10 22H2 in Virtual Machine, only installed .NET9 and the app launches and works normally.

**Comment by Deadfalt999** [comment]
Here's the log




[Log-20250720.txt](https://github.com/user-attachments/files/21334348/Log-20250720.txt)

**Comment by Deadfalt999** [comment]
Also I scrolled up and the terminal gives out this error : 

Unhandled exception. System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.
 ---> System.OverflowException: The image data generated an overflow during processing.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at XeniaManager.Desktop.Views.Windows.MainWindow.InitializeComponent()
   at XeniaManager.Desktop.Views.Windows.MainWindow..ctor()
   at XeniaManager.Desktop.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XeniaManager.Desktop.App.Main()

**Comment by shazzaam7** [comment]
Hi, can you test this [fix](https://github.com/xenia-manager/xenia-manager/actions/runs/16399322504/artifacts/3572164005)?

**Comment by Deadfalt999** [comment]
This actually work, can you sum up what was wrong ? Just want to understand it, thank you again for your patience.

**Comment by shazzaam7** [comment]
Can you give latest experimental build a try too?

**Comment by Deadfalt999** [comment]
Yup that works as well :)

**Comment by shazzaam7** [comment]
Thank you for being patient. Looks like it's fixed now.

**Comment by Deadfalt999** [comment]
No thank you for reopening the ticket when it needed to be xD I still don't understand what the problem was but at least you got it under control. Thank you !
